debug set launcher

diff --git a/roles/all_distros/tasks/main.yml b/roles/all_distros/tasks/main.yml
--- a/roles/all_distros/tasks/main.yml
+++ b/roles/all_distros/tasks/main.yml
@@ -7,45 +7,45 @@
 #  License: MIT
 #
 
-- name: Common apps
-  ansible.builtin.import_tasks: common_apps.yml
+# - name: Common apps
+#   ansible.builtin.import_tasks: common_apps.yml
 
-- name: Configs for /etc
-  ansible.builtin.import_tasks: etc_configs.yml
+# - name: Configs for /etc
+#   ansible.builtin.import_tasks: etc_configs.yml
 
-- name: Run timezone.yml
-  ansible.builtin.import_tasks: timezone.yml
-  when: ift_timezone is defined and ift_timezone
+# - name: Run timezone.yml
+#   ansible.builtin.import_tasks: timezone.yml
+#   when: ift_timezone is defined and ift_timezone
 
-- name: Run services.yml
-  ansible.builtin.import_tasks: services.yml
+# - name: Run services.yml
+#   ansible.builtin.import_tasks: services.yml
 
-- name: Run user_account.yml
-  ansible.builtin.import_tasks: user_account.yml
-  when: ift_user_name is defined and ift_user_name
+# - name: Run user_account.yml
+#   ansible.builtin.import_tasks: user_account.yml
+#   when: ift_user_name is defined and ift_user_name
 
-- name: Run root_shell.yml
-  ansible.builtin.import_tasks: root_shell.yml
-  when: ift_shell is defined and ift_shell
+# - name: Run root_shell.yml
+#   ansible.builtin.import_tasks: root_shell.yml
+#   when: ift_shell is defined and ift_shell
 
-- name: Copy /etc/skel files to root home (without overwrite)
-  ansible.builtin.command: cp -rn /etc/skel/. /root/
-  args:
-    creates: /root/.profile # or any file you expect from skel
-  # become: true
+# - name: Copy /etc/skel files to root home (without overwrite)
+#   ansible.builtin.command: cp -rn /etc/skel/. /root/
+#   args:
+#     creates: /root/.profile # or any file you expect from skel
+#   # become: true
 
 - name: Check if this is iSH
   ansible.builtin.include_tasks: tasks/is_ish.yml
   when: vars['is_ish'] is not defined
 
-- name: "Set chroot default command: {{ f_app_ift_launcher }}"
-  ansible.builtin.copy:
-    dest: /.chroot_default_cmd
-    content: "{{ f_app_ift_launcher }}\n"
-    owner: root
-    group: root
-    mode: "0644"
-  when: not is_ish | default(false)
+# - name: "Set chroot default command: {{ f_app_ift_launcher }}"
+#   ansible.builtin.copy:
+#     dest: /.chroot_default_cmd
+#     content: "{{ f_app_ift_launcher }}\n"
+#     owner: root
+#     group: root
+#     mode: "0644"
+#   when: not is_ish | default(false)
 
 - name: "Enable launcher on iSH: {{ f_app_ift_launcher }}"
   ansible.builtin.shell: |
@@ -54,7 +54,7 @@
     tmp_file=$(mktemp)
     config-ift -l > "$tmp_file" | exit 1
     if grep -qv "{{ f_app_ift_launcher }}" "$tmp_file"; then
-        "{{ f_app_ift_config }}" -l ift | exit 2
+        {{ f_app_ift_config }} -l ift | exit 2
         ex_code=43
     fi
     rm -f "$tmp_file"
@@ -65,36 +65,35 @@
   changed_when: all_distros_launcher.rc == 43
   failed_when: all_distros_launcher.rc not in [0, 43]
   when: is_ish | default(false)
+# - name: Configs Set /etc/ish-fstools-release - {{ vers_ift }}
+#   #
+#   # Do this as late as possible, to only indicate the current
+#   # version once deploy is done
+#   #
+#   # become: true
+#   # become: true
+#   ansible.builtin.shell: |
+#     f_rel_vers=/etc/ish-fstools-release
+#     ex_code=0
 
-- name: Configs Set /etc/ish-fstools-release - {{ vers_ift }}
-  #
-  # Do this as late as possible, to only indicate the current
-  # version once deploy is done
-  #
-  # become: true
-  # become: true
-  ansible.builtin.shell: |
-    f_rel_vers=/etc/ish-fstools-release
-    ex_code=0
+#     input=$(cat "$f_rel_vers")
+#     old_vers_ift=${input%% - *}
+#     rest=${input#* - }
+#     [ "$old_vers_ift" = "$rest" ] && rest=""
 
-    input=$(cat "$f_rel_vers")
-    old_vers_ift=${input%% - *}
-    rest=${input#* - }
-    [ "$old_vers_ift" = "$rest" ] && rest=""
-
-    if [ "$old_vers_ift" != "{{ vers_ift }}" ]; then
-        s="{{ vers_ift }}"
-        if [ -n "$rest" ]; then
-            s="$s - $rest"
-        fi
-        echo "$s" >"$f_rel_vers" || exit 1
-        /usr/local/sbin/update-motd
-        ex_code=43
-    fi
-    exit "$ex_code"
-  args:
-    executable: /bin/bash
-  register: all_distros_rel_vers
-  changed_when: all_distros_rel_vers.rc == 43
-  failed_when:
-    - all_distros_rel_vers.rc not in [0, 43]
+#     if [ "$old_vers_ift" != "{{ vers_ift }}" ]; then
+#         s="{{ vers_ift }}"
+#         if [ -n "$rest" ]; then
+#             s="$s - $rest"
+#         fi
+#         echo "$s" >"$f_rel_vers" || exit 1
+#         /usr/local/sbin/update-motd
+#         ex_code=43
+#     fi
+#     exit "$ex_code"
+#   args:
+#     executable: /bin/bash
+#   register: all_distros_rel_vers
+#   changed_when: all_distros_rel_vers.rc == 43
+#   failed_when:
+#     - all_distros_rel_vers.rc not in [0, 43]
