uptime handled better

diff --git a/roles/alpine/tasks/apps_alpine.yml b/roles/alpine/tasks/apps_alpine.yml
--- a/roles/alpine/tasks/apps_alpine.yml
+++ b/roles/alpine/tasks/apps_alpine.yml
@@ -51,25 +51,25 @@
   changed_when: alpine_old_mtr.rc == 43
   failed_when: alpine_old_mtr.rc not in [0, 43]
 
-- name: Ensure /usr/bin/uptime is symlink to /bin/busybox
-  # The procps uptime throws Segmentation fault on iSH
-  # but the package is generally useful, providing a better ps
-  shell:
-    cmd: |
-      if [ ! -L /usr/bin/uptime ] || \
-        [ "$(readlink -f /usr/bin/uptime)" != "/bin/busybox" ]; then
-          if [ -e /usr/bin/uptime ]; then
-              rm -f /usr/bin/uptime.ORG # only remove .ORG if it will be replaced
-              mv -f /usr/bin/uptime /usr/bin/uptime.ORG || exit 30
-          fi
-          ln -sf /bin/busybox /usr/bin/uptime || exit 31
-          exit 43
-      fi
-  args:
-    executable: /bin/sh
-  register: alpine_rename_uptime
-  changed_when: alpine_rename_uptime.rc == 43
-  failed_when: alpine_rename_uptime.rc not in [0, 43]
+# - name: Ensure /usr/bin/uptime is symlink to /bin/busybox
+#   # The procps uptime throws Segmentation fault on iSH
+#   # but the package is generally useful, providing a better ps
+#   shell:
+#     cmd: |
+#       if [ ! -L /usr/bin/uptime ] || \
+#         [ "$(readlink -f /usr/bin/uptime)" != "/bin/busybox" ]; then
+#           if [ -e /usr/bin/uptime ]; then
+#               rm -f /usr/bin/uptime.ORG # only remove .ORG if it will be replaced
+#               mv -f /usr/bin/uptime /usr/bin/uptime.ORG || exit 30
+#           fi
+#           ln -sf /bin/busybox /usr/bin/uptime || exit 31
+#           exit 43
+#       fi
+#   args:
+#     executable: /bin/sh
+#   register: alpine_rename_uptime
+#   changed_when: alpine_rename_uptime.rc == 43
+#   failed_when: alpine_rename_uptime.rc not in [0, 43]
 
 #
 # The following are Alpine specific, located here to avoid having to split new and
